import trivagoPrettierPluginSortImports from "@trivago/prettier-plugin-sort-imports";
import trivagoPrettierPluginOrganizeImports from "prettier-plugin-organize-imports";

/** @type {import("prettier").Options} */
export default {
  trailingComma: "es5",
  singleQuote: false,
  tabWidth: 2,
  semi: true,
  printWidth: 120,
  useTabs: false,
  jsxSingleQuote: false,
  arrowParens: "avoid",
  singleAttributePerLine: true,
  bracketSpacing: true,
  bracketSameLine: false,
  endOfLine: "lf",
  importOrder: [
    "^react$",
    "<THIRD_PARTY_MODULES>",
    "^@/components/(.*)$",
    "^@/layout/(.*)$",
    "^@/ui/(.*)$",
    "^@/assets/(.*)$",
    "^@/store/(.*)$",
    "^@/hooks/(.*)$",
    "^@/utils/(.*)$",
    "^@/api/(.*)$",
    "(.view)$",
    "(.container)$",
    "(.service)$",
    "(.types)$",
    "(.scss)$",
    "^../(.*)",
    "^./(.*)",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  pluginSearchDirs: false,
  plugins: [trivagoPrettierPluginOrganizeImports, trivagoPrettierPluginSortImports],
};
